### ISSUE TITLE
Credit ouvert

### ISSUE THREAD

**Issue by wafik790** [ITKnowledge/GB-INRH#1]
1. Une seule opération par exercice.
1. Besoin d'une interface dans laquelle on ajoute toutes les rubriques a créditer ou a débiter, a condition que le total soit égale a 0.
1. Il ne faut pas dépasser le montant disponible d'une rubrique.
1. Possibilité de supprimer une opération de virement de credit a condition qu'il n y aura aucun dépassement. 

- [les exercices clôturés ne sont pas concernés par cette opération ]

**Comment by kbellioum** [comment]
This must be in the wiki
